/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example



fun main() {

    val robots = RobotFactory.randomizedRobot()

    val sortedRobots = robots.sortedBy { robot -> robot.getDirection().toString() }

    println("\n\nSorted robots:")
    for (r in sortedRobots) {
        println(r)
    }


    val filteredRobots = robots.filter { robot -> robot.getDirection() == Direction.NORTH && robot.getX() >= 0}
    println("\n\nFiltered robots (facing NORTH and X >= 0):")
    for (r in filteredRobots) {
        println(r)
    }


    val groupedRobots: Map<Direction, List<Robot>> = robots.groupBy { robot -> robot.getDirection() }
    println("\n\nGrouped robots:")
    for ((direction, robotsInDirection) in groupedRobots) {
        println("$direction:")
        for (r in robotsInDirection) {
            println("  $r")
        }
    }


}
